### ISSUE TITLE
Pango and Cairo error

### ISSUE THREAD

**Issue by Karan7040** [Gunjan933/tutorial-pdf-downloader#2]
![IMG_20210108_163944](https://user-images.githubusercontent.com/59613923/104009134-8a48b400-51d0-11eb-9102-9f110c13cf58.jpg)I got this error, any solution?

**Comment by gunjannandy** [comment]
@Karan7040 

Can you please paste the complete error log?

And please also paste the output of -
```bash
pip3 freeze
```

**Comment by Karan7040** [comment]
> @Karan7040
> 
> Can you please paste the complete error log?
> 
> And please also paste the output of -
> 
> ```shell
> pip3 freeze
> ```

C:\Download\tutorial-pdf-downloader-master>pip install --user -r requirements.tx
t
Requirement already satisfied: requests in c:\users\gsaikrishna\appdata\roaming\
python\python37\site-packages (from -r requirements.txt (line 1)) (2.25.1)
Requirement already satisfied: bs4 in c:\users\gsaikrishna\appdata\roaming\pytho
n\python37\site-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: weasyprint in c:\users\gsaikrishna\appdata\roamin
g\python\python37\site-packages (from -r requirements.txt (line 3)) (52.2)
Requirement already satisfied: beautifulsoup4 in c:\users\gsaikrishna\appdata\ro
aming\python\python37\site-packages (from bs4->-r requirements.txt (line 2)) (4.
9.3)
Requirement already satisfied: idna<3,>=2.5 in c:\users\gsaikrishna\appdata\roam
ing\python\python37\site-packages (from requests->-r requirements.txt (line 1))
(2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\gsaikrishna\app
data\roaming\python\python37\site-packages (from requests->-r requirements.txt (
line 1)) (1.26.2)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\gsaikrishna\appdata
\roaming\python\python37\site-packages (from requests->-r requirements.txt (line
 1)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gsaikrishna\appdat
a\roaming\python\python37\site-packages (from requests->-r requirements.txt (lin
e 1)) (2020.12.5)
Requirement already satisfied: cssselect2>=0.1 in c:\users\gsaikrishna\appdata\r
oaming\python\python37\site-packages (from weasyprint->-r requirements.txt (line
 3)) (0.4.1)
Requirement already satisfied: setuptools>=39.2.0 in c:\users\gsaikrishna\appdat
a\roaming\python\python37\site-packages (from weasyprint->-r requirements.txt (l
ine 3)) (51.1.1)
Requirement already satisfied: CairoSVG>=2.4.0 in c:\users\gsaikrishna\appdata\r
oaming\python\python37\site-packages (from weasyprint->-r requirements.txt (line
 3)) (2.5.1)
Requirement already satisfied: html5lib>=0.999999999 in c:\users\gsaikrishna\app
data\roaming\python\python37\site-packages (from weasyprint->-r requirements.txt
 (line 3)) (1.1)
Requirement already satisfied: cairocffi>=0.9.0 in c:\users\gsaikrishna\appdata\
local\programs\python\python37-32\lib\site-packages (from weasyprint->-r require
ments.txt (line 3)) (1.2.0)
Requirement already satisfied: Pillow>=4.0.0 in c:\users\gsaikrishna\appdata\roa
ming\python\python37\site-packages (from weasyprint->-r requirements.txt (line 3
)) (8.1.0)
Requirement already satisfied: tinycss2>=1.0.0 in c:\users\gsaikrishna\appdata\r
oaming\python\python37\site-packages (from weasyprint->-r requirements.txt (line
 3)) (1.1.0)
Requirement already satisfied: Pyphen>=0.9.1 in c:\users\gsaikrishna\appdata\roa
ming\python\python37\site-packages (from weasyprint->-r requirements.txt (line 3
)) (0.10.0)
Requirement already satisfied: cffi>=0.6 in c:\users\gsaikrishna\appdata\roaming
\python\python37\site-packages (from weasyprint->-r requirements.txt (line 3)) (
1.14.4)
Requirement already satisfied: defusedxml in c:\users\gsaikrishna\appdata\roamin
g\python\python37\site-packages (from CairoSVG>=2.4.0->weasyprint->-r requiremen
ts.txt (line 3)) (0.6.0)
Requirement already satisfied: pycparser in c:\users\gsaikrishna\appdata\roaming
\python\python37\site-packages (from cffi>=0.6->weasyprint->-r requirements.txt
(line 3)) (2.20)
Requirement already satisfied: webencodings in c:\users\gsaikrishna\appdata\roam
ing\python\python37\site-packages (from cssselect2>=0.1->weasyprint->-r requirem
ents.txt (line 3)) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\users\gsaikrishna\appdata\roaming\
python\python37\site-packages (from html5lib>=0.999999999->weasyprint->-r requir
ements.txt (line 3)) (1.15.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\gsaikrishna\appdata\roa
ming\python\python37\site-packages (from beautifulsoup4->bs4->-r requirements.tx
t (line 2)) (2.1)

C:\Download\tutorial-pdf-downloader-master>python main.py -j
C:\Users\GSaikrishna\AppData\Roaming\Python\Python37\site-packages\weasyprint\fo
nts.py:41: UserWarning: @font-face support needs Pango >= 1.38
  warnings.warn('@font-face support needs Pango >= 1.38')
C:\Users\GSaikrishna\AppData\Roaming\Python\Python37\site-packages\weasyprint\do
cument.py:36: UserWarning: There are known rendering problems and missing featur
es with cairo < 1.15.4. WeasyPrint may work with older versions, but please read
 the note about the needed cairo version on the "Install" page of the documentat
ion before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.ht
ml
  'There are known rendering problems and missing features with '



C:\Download\tutorial-pdf-downloader-master>pip freeze
beautifulsoup4==4.9.3
bs4==0.0.1
cairocffi==1.2.0
CairoSVG==2.5.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
cssselect2==0.4.1
defusedxml==0.6.0
html5lib==1.1
idna==2.10
pangocairocffi==0.6.0
pangocffi==0.10.0
Pillow==8.1.0
pycairo==1.20.0
pycparser==2.20
Pyphen==0.10.0
requests==2.25.1
six==1.15.0
soupsieve==2.1
tinycss2==1.1.0
urllib3==1.26.2
WeasyPrint==52.2
webencodings==0.5.1

C:\Download\tutorial-pdf-downloader-master>

**Comment by gunjannandy** [comment]
@Karan7040 

Thanks for posting all the details. Unfortunately the issues you are facing are windows specific. I have developed the script in linux, and it works fine there. There are excellent answers in stackoverflow regarding the above issue. One of them is mentioned **[here](https://stackoverflow.com/questions/56704202/failed-to-load-a-library-cairo)**.

Search for **`weasyprint windows issues`**, you will be able to see its a pretty well known issue. 

Do let me know if you could fix the issue. Thanks!

**Comment by Karan7040** [comment]
I tried in Linux too but it didn't work. Please try to resolve this issue and I have even tried to search the error occured in windows but didn't get any solution. 

![IMG-20210108-WA0025](https://user-images.githubusercontent.com/59613923/104093056-14b31580-52ae-11eb-9dca-6acdebc267d5.jpg)

**Comment by gunjannandy** [comment]
Looks like you have not pasted the URL enclosed in **quotation**, in the **[download_links.py](https://github.com/Gunjan933/tutorial-pdf-downloader/blob/master/download_links.py)**. 

Try this, put the link in this format in `download_links.py` file-

```python
download_list = {
	"https://www.javatpoint.com/computer-network-tutorial" ,
}
```

**Comment by Karan7040** [comment]
![Screenshot_20210110-155158~3](https://user-images.githubusercontent.com/59613923/104120339-0ae7eb80-535c-11eb-897f-99c949d03657.png)

Will it ever get done?;(

**Comment by gunjannandy** [comment]
@Karan7040 I hope the solution worked for you. Closing the issue for now, you can reopen it anytime.

**Comment by sfksuperman** [comment]
I got similar issue when I run the script. I guess it's not working at all. I also put the link in double quotes that we all know. But there must be a video tutorial about the steps how to execute it all.
I got 3.9.6 python installed already but still nothing is working.

**Comment by Karan7040** [comment]
> I got similar issue when I run the script. I guess it's not working at all. I also put the link in double quotes that we all know. But there must be a video tutorial about the steps how to execute it all.
> I got 3.9.6 python installed already but still nothing is working.
Try to install WeasyPrint, it will work.
